import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../../component/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});




export const metadata = {
  title: "BNMI INDIA",
  description: "Generated by create next app",
  img: "https://share.google/sRhRST9z6i9XuTusX",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navbar />
        <body
  className={`${geistSans.variable} ${geistMono.variable}`}
  style={{ color: "#000", background: "#fff" }}

      >

        {children}
      </body>
    </html>
  );
}
